apiVersion: v1
kind: Service
metadata:
  name: webhook-sidecard
  namespace: kubevirt-webhooks
spec:
  selector:
    app: webhook-sidecard
  ports:
    - port: 443
      targetPort: webhook
      name: https
